### ISSUE TITLE
Dataset format issues

### ISSUE THREAD

**Issue by Anorid** [WalkerMitty/Fast-Llama2#2]
(p) root@autodl-container-52e511a3ae-8cacdb5e:~/autodl-tmp/Fast-Llama2# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_port=6006 finetuning.py --enable_fsdp --model_name /root/autodl-tmp/llama2-7b --peft_method lora --use_peft true --save_model --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --fsdp_config.pure_bf16 --lr 5e-6 --output_dir /root/autodl-tmp/llama2-7b --train_split /root/autodl-tmp/Fast-Llama2/data/demo_train.json --batch_size_training 16 --lora_path '' --step_size 1 --num_epochs 1
Warning: unknown parameter train_split
Clearing GPU cache for all ranks
--> Running with torch dist debug set to detail
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.79s/it]
--> Model /root/autodl-tmp/llama2-7b

--> /root/autodl-tmp/llama2-7b has 6738.415616 Million params

初始化LORA权重……
trainable params: 8,388,608 || all params: 6,746,804,224 || trainable%: 0.12433454005023165
bFloat16 enabled for mixed precision - using bfSixteen policy
--> applying fsdp activation checkpointing...
Traceback (most recent call last):
  File "/root/autodl-tmp/Fast-Llama2/finetuning.py", line 242, in <module>
    fire.Fire(main)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/autodl-tmp/Fast-Llama2/finetuning.py", line 174, in main
    dataset_train = get_preprocessed_dataset(
  File "/root/autodl-tmp/Fast-Llama2/llama_recipes/utils/dataset_utils.py", line 73, in get_preprocessed_dataset
    return DATASET_PREPROC[dataset_config.dataset](
  File "/root/autodl-tmp/Fast-Llama2/llama_recipes/datasets/samsum_dataset.py", line 11, in get_preprocessed_samsum
    dataset = datasets.load_dataset("samsum", split=split)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/datasets/load.py", line 2595, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/datasets/builder.py", line 1244, in as_dataset
    datasets = map_nested(
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 457, in map_nested
    return function(data_struct)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/datasets/builder.py", line 1271, in _build_single_dataset
    split = Split(split)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/datasets/splits.py", line 451, in __new__
    return NamedSplitAll() if name == "all" else NamedSplit(name)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/datasets/splits.py", line 362, in __init__
    raise ValueError(f"Split name should match '{_split_re}' but got '{split_name}'.")
ValueError: Split name should match '^\w+(\.\w+)*$' but got '/root/autodl-tmp/Fast-Llama2/data/demo_train.json'.
[2024-04-08 10:36:51,949] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 38677) of binary: /root/miniconda3/envs/p/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/p/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/p/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetuning.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-08_10:36:51
  host      : autodl-container-52e511a3ae-8cacdb5e
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 38677)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
--------------------------------------------------------------------------------------------------------------
Try to test according to the author's data, and the error will be reported when the whole runs, and the above is the error situation, and the error seems to be a format problem, and I didn't modify the content of the demo_json, but it still reported an error

**Comment by WalkerMitty** [comment]
Sorry, I forgot to mention that the dataset size must be greater than ``num_gpus * batch_size``. I have updated the demo_train accordingly. Additionally, I suggest you follow my environment setup, which I have updated in the readme.
Please let me know if there are any other issues.

**Comment by WalkerMitty** [comment]
Since this issue is no longer active, I have closed it.
